site_name: ENLIGHT
site_description: European Network for Long-term Insights on Grid prices, Hedging & Trends
site_author: Marco Saretta
repo_url: https://github.com/marco-saretta-DTU/enlight
repo_name: marco-saretta-DTU/enlight
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.sections
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - Reference:
    - Configuration: configuration.md
